// next/src/PrivacyPolicy.tsx
import { ScadablePolicy, forDocType } from './ScadablePolicy';
import type { NamedDocumentProps } from './ScadablePolicy';

/** Props for <PrivacyPolicy>: a `token` or a `tenant`, with the document fixed to "privacy_policy". */
export type PrivacyPolicyProps = NamedDocumentProps;

/**
 * Renders your always-current privacy policy. A thin wrapper over {@link ScadablePolicy}
 * with `docType` fixed to "privacy_policy"; see that component for the hybrid SEO + live
 * behavior.
 *
 * ```tsx
 * import { PrivacyPolicy } from '@scadable/next';
 *
 * export default function PrivacyPage() {
 *   return <PrivacyPolicy token="YOUR_PUBLIC_TOKEN" />;
 * }
 * ```
 */
export function PrivacyPolicy(props: PrivacyPolicyProps) {
  return ScadablePolicy(forDocType(props, 'privacy_policy'));
}

// svelte/src/PrivacyPolicy.svelte
<script>
  // Renders your always-current privacy policy. Token-only:
  // `<PrivacyPolicy token="YOUR_PUBLIC_TOKEN" />`. A thin wrapper over
  // ScadablePolicy with docType locked to "privacy_policy".
  import ScadablePolicy from './ScadablePolicy.svelte';

  /** The public token from the SCADABLE app. */
  export let token;
  /** HTML rendered before the live fetch resolves (e.g. baked in by SvelteKit SSR for SEO). */
  export let initialHtml = '';
  /** Class on the wrapper element so you can style/position the document. */
  let className = '';
  export { className as class };
</script>

<ScadablePolicy {token} docType="privacy_policy" {initialHtml} class={className} />
