// react/src/TermsOfUse.tsx
'use client';

import * as React from 'react';

import { ScadablePolicy } from './ScadablePolicy';
import type { ScadablePolicyProps } from './ScadablePolicy';

export type TermsOfUseProps = Omit<ScadablePolicyProps, 'docType'>;

/**
 * Renders your always-current terms of use. A thin wrapper around
 * {@link ScadablePolicy} with `docType` pinned to "terms_of_use".
 *
 * ```tsx
 * import { TermsOfUse } from '@scadable/react';
 *
 * export default function TermsPage() {
 *   return <TermsOfUse token="YOUR_PUBLIC_TOKEN" />;
 * }
 * ```
 */
export function TermsOfUse(props: TermsOfUseProps) {
  return <ScadablePolicy {...props} docType="terms_of_use" />;
}

// svelte/src/TermsOfUse.svelte
<script>
  // Renders your always-current terms of use. Token-only:
  // `<TermsOfUse token="YOUR_PUBLIC_TOKEN" />`. A thin wrapper over ScadablePolicy
  // with docType locked to "terms_of_use".
  import ScadablePolicy from './ScadablePolicy.svelte';

  /** The public token from the SCADABLE app. */
  export let token;
  /** HTML rendered before the live fetch resolves (e.g. baked in by SvelteKit SSR for SEO). */
  export let initialHtml = '';
  /** Class on the wrapper element so you can style/position the document. */
  let className = '';
  export { className as class };
</script>

<ScadablePolicy {token} docType="terms_of_use" {initialHtml} class={className} />
