// svelte/src/ScadablePolicy.svelte
<script>
  // Renders your always-current SCADABLE document (privacy policy, terms of use, ...)
  // pulled live from the SCADABLE API.
  //
  // Zero-friction: give it your public token and you are done. If you pass
  // `initialHtml` (for example from a SvelteKit `load` server fetch) it renders that
  // immediately, so the legal text and the "by scadable.com" backlink are in the
  // server HTML for SEO and the page paints with no layout shift. On mount it
  // re-fetches the live document so edits you publish in SCADABLE go live with no
  // redeploy on your side. If the browser fetch is blocked (a strict
  // Content-Security-Policy) or offline, the baked copy stays put, so the page is
  // never blank.
  //
  // Svelte 4 syntax, which also runs under Svelte 5 in legacy mode.
  import { onMount } from 'svelte';
  import { fetchPolicy } from '@scadable/core';

  /** The public token from the SCADABLE app. */
  export let token;
  /** Which document to render. Default "privacy_policy". */
  export let docType = 'privacy_policy';
  /** HTML rendered before the live fetch resolves (e.g. baked in by SvelteKit SSR for SEO). */
  export let initialHtml = '';
  /** Class on the wrapper element so you can style/position the document. */
  let className = '';
  export { className as class };

  let html = initialHtml;

  onMount(() => {
    fetchPolicy(token, { docType, revalidate: false })
      .then((policy) => {
        if (policy && policy.html) html = policy.html;
      })
      .catch(() => {
        /* keep the baked copy if the browser fetch is blocked (CSP) or offline */
      });
  });
</script>

<div class={className}>{@html html}</div>

// next/src/ScadablePolicy.tsx
import { fetchPolicy } from '@scadable/core';
import type { FetchPolicyOptions } from '@scadable/core';

import { PolicyLive } from './PolicyLive';

export interface ScadablePolicyProps extends FetchPolicyOptions {
  /** The public token from the SCADABLE app. */
  token: string;
  /** Optional wrapper class so you can style/position the document. */
  className?: string;
  /** Show a small "Version N, last updated ..." line under the document. Default false. */
  showVersion?: boolean;
}

/**
 * Renders your always-current SCADABLE document for any `docType`.
 *
 * Hybrid by design. The document HTML is fetched at build / server-render time and baked
 * into the static HTML, so the legal text and the "by scadable.com" backlink are
 * crawlable for SEO and paint instantly. It is then re-fetched in the browser (see
 * {@link PolicyLive}) so edits you make in SCADABLE go live with no redeploy on your
 * side. If a strict Content-Security-Policy blocks the browser fetch, the baked copy
 * stays put, so the page is never blank.
 *
 * `docType` defaults to "privacy_policy". Use the {@link PrivacyPolicy} and
 * {@link TermsOfUse} wrappers for the common cases, or set `docType` directly here for
 * any future document type.
 *
 * ```tsx
 * import { ScadablePolicy } from '@scadable/next';
 *
 * export default function Page() {
 *   return <ScadablePolicy token="YOUR_PUBLIC_TOKEN" docType="terms_of_use" />;
 * }
 * ```
 */
export async function ScadablePolicy({
  token,
  className,
  showVersion = false,
  docType = 'privacy_policy',
  ...options
}: ScadablePolicyProps) {
  const policy = await fetchPolicy(token, { ...options, docType });
  return (
    <PolicyLive
      token={token}
      initialHtml={policy.html}
      initialVersion={policy.version}
      initialUpdatedAt={policy.updated_at}
      className={className}
      showVersion={showVersion}
      baseUrl={options.baseUrl}
      docType={docType}
    />
  );
}
