// svelte/src/TermsOfUse.svelte
<script>
  // Renders your always-current terms of use. Token-only:
  // `<TermsOfUse token="YOUR_PUBLIC_TOKEN" />`. A thin wrapper over ScadablePolicy
  // with docType locked to "terms_of_use".
  import ScadablePolicy from './ScadablePolicy.svelte';

  /** The public token from the SCADABLE app. */
  export let token;
  /** HTML rendered before the live fetch resolves (e.g. baked in by SvelteKit SSR for SEO). */
  export let initialHtml = '';
  /** Class on the wrapper element so you can style/position the document. */
  let className = '';
  export { className as class };
</script>

<ScadablePolicy {token} docType="terms_of_use" {initialHtml} class={className} />

// next/src/TermsOfUse.tsx
import { ScadablePolicy, forDocType } from './ScadablePolicy';
import type { NamedDocumentProps } from './ScadablePolicy';

/** Props for <TermsOfUse>: a `token` or a `tenant`, with the document fixed to "terms_of_use". */
export type TermsOfUseProps = NamedDocumentProps;

/**
 * Renders your always-current terms of use. A thin wrapper over {@link ScadablePolicy}
 * with `docType` fixed to "terms_of_use"; see that component for the hybrid SEO + live
 * behavior.
 *
 * ```tsx
 * import { TermsOfUse } from '@scadable/next';
 *
 * export default function TermsPage() {
 *   return <TermsOfUse token="YOUR_PUBLIC_TOKEN" />;
 * }
 * ```
 */
export function TermsOfUse(props: TermsOfUseProps) {
  return ScadablePolicy(forDocType(props, 'terms_of_use'));
}
